{
 "title": "Loki Stack Monitoring",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki.",
 "tags": [
  "loki",
  "promtail",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Summary of alerts status",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Problems in the Loki Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loki - Error/Warning Messages Logged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total{job=\"loki\",level=~\"error|warn\"}[1m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Loki - Error/Warning Messages Logged",
   "type": "logs",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"/loki\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Promtail - Error/Warning Messages Logged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total{job=\"promtail\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Promtail - Error/Warning Messages Logged",
   "type": "logs",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"/promtail\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Promtail - Dropped Log Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(promtail_dropped_entries_total)",
     "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
    }
   ]
  },
  {
   "title": "Logging Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Streams in Loki",
   "type": "timeseries",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_memory_streams[1m])",
     "legendFormat": "Streams"
    }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "timeseries",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "timeseries",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  }
 ]
}